version: 0.2
env:
  secrets-manager:
    VITE_FRONT_END_AWS_GATEWAY_API_KEY: arn:aws:secretsmanager:us-east-1:471808368523:secret:prod/kiosk/apikey-OjfwSl:VITE_FRONT_END_AWS_GATEWAY_API_KEY
phases:
  install:
    runtime-versions:
      node: 20.9.0
    commands:
      - echo "Installing application server dependencies"
      - cd shared/server
      - npm install
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 471808368523.dkr.ecr.us-east-1.amazonaws.com/kiosk:latest
      - REPOSITORY_URI=471808368523.dkr.ecr.us-east-1.amazonaws.com/kiosk
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo "Buiding web application docker container"
      - docker build -t $REPOSITORY_URI:latest -f ./Dockerfile.prod --build-arg VITE_FRONT_END_SERVER_URL=${VITE_FRONT_END_SERVER_URL} --build-arg VITE_FRONT_END_AWS_GATEWAY_API_KEY=${VITE_FRONT_END_AWS_GATEWAY_API_KEY} .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo ${VITE_FRONT_END_AWS_GATEWAY_API_KEY}
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"kiosk","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json