FROM node:18.17.1-alpine as build 
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./shared/package.json /app/
COPY ./shared/package-lock.json /app/
RUN npm install
COPY ./shared /app
RUN npm run build

# Kick them tires
FROM nginx:latest
COPY --from=build /app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ./shared/nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
